import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

const frontendRoot = path.resolve(new URL('..', import.meta.url).pathname);
const sourceRoot = path.join(frontendRoot, 'src');
const read = (file) => fs.readFileSync(path.join(sourceRoot, file), 'utf8');

const api = read('api.ts');
const store = read('store.ts');
const style = read('style.css');
const mainPage = read('views/MainPage.vue');
const settingsPage = read('views/SettingsPage.vue');
const rootApp = read('App.vue');
const runtime = read('runtime.ts');
const appBar = read('views/AppBar.vue');
const publicIcon = fs.readFileSync(path.join(frontendRoot, 'public/icon.svg'), 'utf8');
const switchComponent = read('ui/SlSwitch.vue');
const sliderComponent = read('ui/SlSlider.vue');
const selectComponent = read('ui/SlSelect.vue');
const slListView = read('ui/SlListView.vue');
const slButton = read('ui/SlButton.vue');
const slIcon = read('ui/SlIcon.vue');
const playerBar = read('views/PlayerBar.vue');
const fullscreenPlayer = read('views/FullscreenPlayer.vue');
const voiceSettings = read('views/settings/VoiceSettings.vue');
const modePopup = read('views/PlayerModePopup.vue');
const toolboxSettings = read('views/settings/ToolboxSettings.vue');
const volumePopup = read('views/PlayerVolumePopup.vue');
const sleepTimerPopup = read('views/PlayerSleepTimerPopup.vue');
const progress = read('views/PlayerProgress.vue');
const songRow = read('views/SongRow.vue');
const covers = read('covers.ts');
const playlistHandler = fs.readFileSync(path.join(frontendRoot, '../src/handlers/playlist.ts'), 'utf8');
const lyricHandler = fs.readFileSync(path.join(frontendRoot, '../src/handlers/lyric.ts'), 'utf8');
const voiceCommandHandler = fs.readFileSync(path.join(frontendRoot, '../src/handlers/voice_command.ts'), 'utf8');
const voiceEngine = fs.readFileSync(path.join(frontendRoot, '../src/voicecmd/engine.ts'), 'utf8');
const playerManager = fs.readFileSync(path.join(frontendRoot, '../src/player/manager.ts'), 'utf8');
const pluginTypes = fs.readFileSync(path.join(frontendRoot, '../src/types.ts'), 'utf8');
const favorites = fs.readFileSync(path.join(frontendRoot, '../src/utils/favorites.ts'), 'utf8');
const app = fs.readFileSync(path.join(frontendRoot, '../static/js/app.js'), 'utf8');
const html = fs.readFileSync(path.join(frontendRoot, '../static/index.html'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(frontendRoot, '../plugin.json'), 'utf8'));

assert.equal(manifest.renderEngine, 'webf');
assert.match(html, /static\/js\/app\.js/);
assert.match(html, /static\/css\/style\.css/);
assert.match(api, /apiGet\(path\)/);
assert.match(api, /postEnvelope/);
assert.match(store, /status\/ws/);
assert.match(store, /startStatusPolling/);
assert.match(store, /external_search_sources/);
assert.match(store, /selectCurrentPlaylistOnEntry/);
assert.match(store, /await selectCurrentPlaylistOnEntry\(\)/);
assert.match(store, /pendingConfigPatch/);
assert.match(store, /while \(pendingConfigPatch\)/);
assert.doesNotMatch(switchComponent, /flutter-cupertino-switch/);
assert.match(selectComponent, /getBoundingClientRect\(\)\.width/);
assert.match(selectComponent, /sl-select-option-on/);
assert.match(selectComponent, /sl-select-wrap-open/);
assert.match(mainPage, /openSelect\.value = null/);
assert.match(mainPage, /@click="openDevicePicker"/);
assert.match(style, /\.sl-select-wrap-open\s*\{\s*z-index: 80/);
assert.match(style, /\.miot-main-appbar[\s\S]*position: fixed/);
assert.match(style, /html\.webf-engine \.miot-app \* \{ transform-origin: 0 0; \}/);
assert.match(style, /html\.webf-engine \.player-volume-slider[^}]*transform: none/);
assert.match(style, /\.settings-scroll-body[^}]*height: calc\(100dvh - 56px\)[^}]*overflow-y: auto/);
assert.match(style, /\.switch-track::after[^}]*transition: transform/);
assert.match(style, /\.switch input:checked ~ \.switch-track::after[^}]*translateX\(20px\)/);
assert.match(settingsPage, /class="settings-scroll-body"/);
assert.match(settingsPage, /openSelect\.value = null/);
assert.match(settingsPage, /<AppBar :title="appbarTitle" back @back="back"/);
assert.match(settingsPage, /window\.innerWidth < 600/);
assert.match(style, /--miot-nav-width: 280px/);
assert.match(style, /\.settings-nav-item[^}]*min-height: 60px[^}]*padding: 10px 16px/);
assert.match(style, /\.settings-mobile-menu \.settings-nav-title[^}]*font-size: 16px[^}]*line-height: 24px/);
assert.match(runtime, /page: 'main' as AppPage/);
assert.match(runtime, /export function openPage/);
assert.match(runtime, /export function closePage/);
assert.match(rootApp, /v-if="navigation\.page === 'settings'"/);
assert.match(rootApp, /v-else-if="navigation\.page === 'player'"/);
assert.doesNotMatch(rootApp, /settingsOpen|playerOpen/);
assert.doesNotMatch(style, /\.page-overlay/);
assert.doesNotMatch(appBar, /<SlIcon|name="speaker"/);
assert.doesNotMatch(publicIcon, /<circle/);
assert.match(publicIcon, /viewBox="0 -960 960 960"/);
assert.match(publicIcon, /<path[^>]+fill="#191C20"/);
assert.match(publicIcon, /M680-80H280/);
assert.match(mainPage, /icon="speaker_group" title="选择设备"/);
assert.doesNotMatch(mainPage, /title="URL 播放"|title="文字播报"/);
assert.match(mainPage, /measureListHeight/);
assert.match(mainPage, /listBottom - listTop/);
assert.match(mainPage, /window\.addEventListener\('resize', remeasureList\)/);
assert.match(mainPage, /miot-page-with-player/);
assert.match(style, /--miot-list-height: clamp\(240px, calc\(100vh - 254px\), 720px\)/);
assert.match(style, /\.sl-list-view\s*\{[^}]*height: var\(--miot-list-height\)/);
assert.match(slListView, /class="sl-list-view sl-list-view-html"/);
assert.doesNotMatch(slListView, /webf-list-view/);
assert.doesNotMatch(mainPage, /:height="'var\(--miot-list-height\)'"/);
assert.match(mainPage, /songRenderLimit = ref\(20\)/);
assert.match(mainPage, /visibleSongs\.value\.slice\(0, songRenderLimit\.value\)/);
assert.match(mainPage, /songRenderLimit\.value = Math\.min\(songRenderLimit\.value \+ songRenderBatchSize/);
assert.match(slListView, /defineEmits<\{ scroll/);
assert.match(style, /\.player-bar-shell[\s\S]*position: fixed/);
assert.match(style, /\.song-cover[^}]*width: 48px[^}]*height: 48px/);
assert.match(songRow, /class="song-cover-img"/);
assert.match(songRow, /acquireCoverSlot/);
assert.match(covers, /access_token/);
assert.match(covers, /MAX_CONCURRENT_COVERS = 3/);
assert.match(playerBar, /songCoverUrl\(state\.player\.current_song, 96\)/);
assert.match(fullscreenPlayer, /songCoverUrl\(state\.player\.current_song, 768\)/);
assert.match(playerBar, /@error="coverFailed = true"/);
assert.match(fullscreenPlayer, /@error="coverFailed = true"/);
assert.match(voiceSettings, /class="command-keywords"/);
assert.match(voiceSettings, /addKeyword\(command, index\)/);
assert.match(voiceSettings, /removeKeyword\(command, index, keywordIndex\)/);
assert.match(voiceSettings, /setCommandEnabled\(index, \$event\)/);
assert.match(voiceSettings, /saveVoiceCommands\(\[\]\)/);
assert.match(voiceSettings, /device_id: state\.currentDeviceId/);
assert.match(voiceSettings, /account_id: state\.currentAccountId/);
assert.match(voiceSettings, /commandInputVersions/);
assert.match(style, /\.inline-fields\s*\{[^}]*flex-wrap: wrap/);
assert.match(style, /\.card\.miot-card\s*\{[^}]*padding: 0/);
assert.match(style, /\.player-mini-progress[\s\S]*height: 2px/);
assert.match(playerBar, /<PlayerProgress[\s\S]*mini/);
assert.match(playerBar, /@click="openPlayer"/);
assert.doesNotMatch(playerBar, /setVolume|open_in_full/);
assert.doesNotMatch(playerBar, /mini-mode-control|mini-stop-control/);
assert.match(modePopup, /value: 'single'/);
assert.match(modePopup, /value: 'random'/);
assert.match(modePopup, /value: 'singlePlay'.*label: '单曲播放'.*icon: 'looks_one'/);
assert.doesNotMatch(modePopup, /value: 'repeat_one'|value: 'shuffle'/);
assert.match(modePopup, /const panelWidth = mobile \? 140 : 160/);
assert.match(modePopup, /height: `\$\{panelHeight\}px`/);
assert.match(modePopup, /Math\.max\(edgeInset, Math\.min\(centeredLeft/);
assert.match(modePopup, /aboveTop < edgeInset \? rect\.bottom \+ gap : aboveTop/);
assert.match(style, /\.player-mode-popup\s*\{[^}]*position: fixed[^}]*width: 160px/);
assert.match(style, /@media \(max-width: 599px\)[\s\S]*\.player-mode-popup\s*\{[^}]*width: 140px/);
assert.match(style, /@media \(max-width: 599px\)[\s\S]*\.player-mode-option\s*\{[^}]*height: 44px/);
assert.match(toolboxSettings, /ref\('https:\/\/lhttp\.qtfm\.cn\/live\/4915\/64k\.mp3'\)/);
assert.doesNotMatch(toolboxSettings, /sendUrl[\s\S]*url\.value = ''[\s\S]*catch/);
assert.match(pluginTypes, /'singlePlay'/);
assert.match(playerManager, /case 'singlePlay'[\s\S]*return 'singlePlay'/);
assert.match(playerManager, /this\.playMode === 'singlePlay'[\s\S]*this\.currentIndex \+ 1/);
assert.match(playerManager, /Single-play completed, pausing on current song/);
assert.match(fullscreenPlayer, /<PlayerModePopup/);
assert.match(fullscreenPlayer, /<PlayerVolumePopup/);
assert.match(fullscreenPlayer, /<PlayerSleepTimerPopup/);
assert.match(fullscreenPlayer, /action: next \? 'add' : 'remove'/);
assert.match(fullscreenPlayer, /isFavorite\.value = next/);
assert.match(fullscreenPlayer, /class="player-favorite-button"/);
assert.match(fullscreenPlayer, /class="fullscreen-tool-desktop player-favorite-button"/);
assert.equal((fullscreenPlayer.match(/player-icon/g) || []).length, 12);
assert.match(slButton, /playerIcon\?: boolean/);
assert.match(slButton, /:player-icon="playerIcon"/);
assert.match(slIcon, /favorite: 0xe25b/);
assert.match(slIcon, /looks_one: 0xf19e/);
assert.doesNotMatch(modePopup, /looks_one_outlined/);
assert.match(style, /\.player-favorite-button\.player-control-active \.sl-icon[^}]*font-variation-settings: 'FILL' 1/);
assert.match(slIcon, /import \{ isWebFRuntime \} from '\.\.\/runtime'/);
assert.match(slIcon, /props\.playerIcon && !isWebFRuntime/);
assert.match(slIcon, /String\.fromCodePoint/);
assert.match(style, /\.material-symbols-outlined\.sl-icon-material-player[^}]*font-family: 'Material Icons Player'/);
assert.match(style, /material-icons-player\.otf/);
assert.match(style, /\.player-favorite-button\.player-control-active[^}]*#f44336/);
assert.match(sleepTimerPopup, /status\.active \? 'alarm_on' : 'alarm'/);
assert.match(sleepTimerPopup, /choose\('time', 15\)/);
assert.match(sleepTimerPopup, /choose\('songs', 5\)/);
assert.match(style, /\.player-sleep-popup[^}]*width: 280px[^}]*max-width: calc\(100vw - 32px\)/);
assert.match(sleepTimerPopup, /navigation\.playerPopup = props\.popupId;\s*emit\('refresh'\)/);
assert.match(style, /\.fullscreen-stage\s*\{\s*flex: 1 1 0%/);
assert.match(style, /\.fullscreen-mobile-slide \.fullscreen-cover-frame[^}]*height: 72vw[^}]*max-height: 320px/);
assert.match(style, /\.fullscreen-layout[^}]*padding-bottom: calc\(228px \+ var\(--sl-safe-bottom/);
assert.match(style, /\.fullscreen-playback[^}]*position: fixed[^}]*bottom: var\(--sl-safe-bottom[^}]*height: 228px/);
assert.match(fullscreenPlayer, /@seek="seekPlayer"/);
assert.match(fullscreenPlayer, /class="fullscreen-desktop-stage"/);
assert.match(fullscreenPlayer, /class="fullscreen-mobile-pager"/);
assert.match(fullscreenPlayer, /currentPager\.scrollLeft = target/);
assert.match(fullscreenPlayer, /pager\.scrollLeft = pager\.clientWidth \* index/);
assert.match(fullscreenPlayer, /mobileSettledPage === 0[\s\S]*ratio >= 0\.12[\s\S]*ratio <= 0\.88/);
assert.match(fullscreenPlayer, /@scroll\.passive="syncMobilePage"/);
assert.match(fullscreenPlayer, /icon="keyboard_arrow_down"/);
assert.doesNotMatch(fullscreenPlayer, /AppBar|正在播放/);
assert.match(fullscreenPlayer, /@touchstart\.passive="startMobileSwipe"/);
assert.match(fullscreenPlayer, /@touchend="finishMobileSwipe"/);
assert.doesNotMatch(fullscreenPlayer, /scrollIntoView/);
assert.match(fullscreenPlayer, /panel\.scrollTo\(\{ top:/);
assert.match(fullscreenPlayer, /result\.lyric \|\| result\.lxlyric/);
assert.match(lyricHandler, /success: true,[\s\S]*data: \{[\s\S]*lyric:/);
assert.match(fullscreenPlayer, /showMobilePage\(1\)/);
assert.match(fullscreenPlayer, /class="fullscreen-controls fullscreen-controls-desktop"/);
assert.match(fullscreenPlayer, /class="fullscreen-controls fullscreen-controls-mobile"/);
assert.match(style, /\.fullscreen-player\s*\{[^}]*height: 100dvh[^}]*overflow: hidden/);
assert.match(style, /\.fullscreen-desktop-stage\s*\{[^}]*grid-template-columns/);
assert.match(style, /\.fullscreen-mobile-pager\s*\{[^}]*scroll-behavior: auto/);
assert.match(modePopup, /player-mode-popup/);
assert.match(volumePopup, /player-volume-popup/);
assert.match(volumePopup, /orientation="vertical"/);
assert.match(sliderComponent, /orientation: props\.orientation/);
assert.match(volumePopup, /function clampVolume\(value: number\)/);
assert.match(volumePopup, /ref\(clampVolume\(props\.modelValue\)\)/);
assert.match(progress, /player-seek-input/);
assert.match(playlistHandler, /router\.post\('\/player\/seek'/);
assert.match(playlistHandler, /songloft\.playlists\.addSongs\(favPlaylist\.id, \[songId\]\)/);
assert.match(playlistHandler, /songloft\.playlists\.removeSongs\(favPlaylist\.id, \[songId\]\)/);
assert.match(favorites, /playlist\.id === 1/);
assert.match(voiceCommandHandler, /router\.post\('\/voice-commands\/sleep-timer'/);
assert.match(voiceEngine, /setSleepTimer\(/);
assert.match(playlistHandler, /status\.state === 'stopped'/);
assert.match(app, /MIoT/);
assert.ok(app.length > 50000, '生产 bundle 过小，可能没有包含 Vue 页面');

const clamp = (value, min, max) => Math.max(min, Math.min(max, value));
assert.equal(clamp(120, 0, 100), 100);
assert.equal(clamp(-1, 0, 100), 0);
assert.equal(clamp(42, 0, 100), 42);

console.log('miot frontend contract tests passed');
